services:
  - type: web
    name: valentine-matcher
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn valentine.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: valentine-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true

databases:
  - name: valentine-db
    databaseName: valentine
    user: valentine