services:
  - type: web
    name: valentine-matcher
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn valentine.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: valentine-db
          property: connectionString
    buildEnv:
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: valentine-db
    databaseName: valentine
    user: valentine
    plan: free