# Generated by Django 5.1.6 on 2025-02-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='personlity_traits',
            new_name='personality_traits',
        ),
    ]
