# Generated by Django 5.1.6 on 2025-02-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearts', '0003_alter_profile_zodiac_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personality_traits',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=100),
        ),
    ]
