# Generated by Django 5.1.6 on 2025-02-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearts', '0004_alter_profile_personality_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='personality_traits',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.CharField(blank=True, choices=[('MALE', 'Men'), ('FEMALE', 'Women'), ('BOTH', 'Both'), ('OTHER', 'Other')], max_length=6),
        ),
    ]
