# Generated by Django 5.1.6 on 2025-02-08 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearts', '0005_remove_profile_personality_traits_profile_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresponse',
            old_name='Question',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('user', 'question')},
        ),
    ]
